version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
#    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./:/var/www
    ports:
      - 8001:8000
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=blog_test"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    links:
      - mysql

    # Web Server
  nginx:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    links:
      - app
    ports:
      - 8002:80

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: blog_test
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    # Database management
  pma:
    image: phpmyadmin:5.1
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    links:
      - mysql
    ports:
      - 8888:80

volumes:
  dbdata:
