version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
#    command: 'php artisan migrate'
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db

    # Web Server
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app
    ports:
      - 80:80

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
    # Database management
  pma:
    image: phpmyadmin:5.1
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=root
      - PMA_PORT=${DB_PORT}
    depends_on:
      - db
    ports:
      - 8888:80

volumes:
  dbdata:
